#!/bin/bash
rm -rf dist
VERSION=`git describe --tags`
python2 setup-release.py py2app
hdiutil create -fs HFS+ -volname "Electrum-MRNG" -srcfolder dist/Electrum-MRNG.app dist/electrum-mrng-$VERSION.dmg

